spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: quiz-service
          uri: lb://QUIZ-SERVICE
          predicates:
            - Path=/quiz/**

        - id: QUESTION-SERVICE
          uri: lb://QUESTION-SERVICE
          predicates:
            - Path=/question/**

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: TRACE
