spring:
  application:
    name: SERVICE-REGISTRY

# Disable as Client
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
#    register-with-eureka: false

server:
  port: 8761
